pipeline {
    agent {
        docker { 
            image 'bedinotom/pythondsd:3.10.11-bullseye'
            args '--pull=always'
        }
    }
    stages {
        stage('Setup environnement') {
            steps {
                sh 'python -m venv .'
                sh '. ./bin/activate'
                sh 'sudo pip install flake8'
                sh 'sudo pip install -r requirements.txt'
            }
        }
        stage('Check Unit Test Web') {
            steps {
                sh 'pytest ./tests'
            }
        }
        stage('Check Style') {
            steps {
                sh 'flake8 ./app'
            }
        }
    }
    post {
        always {
            deleteDir() /* clean up our workspace */
        }
    }
}